spring.application.name=raizes

# 1. Configuração de Conexão com o Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/raizesdb
spring.datasource.username=postgres
spring.datasource.password=postgres

# 2. Exibir os comandos SQL no terminal (Ajuda a ver se a tabela foi criada)
spring.jpa.show-sql=true

# 3. Forçar a criação das tabelas lendo as classes Java com o @Entity
spring.jpa.hibernate.ddl-auto=update

# 4. Dialeto do PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 5. Configurações para ler o arquivo data.sql corretamente
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8