spring.application.name=raizes

spring.datasource.url=jdbc:postgresql://localhost:5432/raizesdb

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


spring.jpa.show-sql=true


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Garante que o arquivo data.sql rode no Postgres DEPOIS que as tabelas forem criadas
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true