spring.application.name=raizes

#  Configuração de Conexão com o Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/raizesdb
spring.datasource.username=postgres
spring.datasource.password=sua_senha

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações para ler o arquivo data.sql corretamente
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8